routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'DashboardController@index')->name('home');
// Admin Security
Route::resource('logs', 'LogController');
Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
// Product API
Route::put('product-restore/{id}','ProductController@rest')->name('products.restore');
Route::get('products/inventory','ProductController@listofinventory')->name('inventory.list');
Route::get('products/archive','ProductController@archive')->name('products.archive');
Route::get('products/create/raw','ProductController@createraw')->name('products.raw.create');
Route::resource('products', 'ProductController');
// Category API
Route::put('category-restore/{id}','CategoryController@rest')->name('categories.restore');
Route::get('categories/archive','CategoryController@archive')->name('categories.archive');
Route::resource('categories', 'CategoryController');
// Supplier API
Route::put('supplier-restore/{id}','SupplierController@rest')->name('suppliers.restore');
Route::get('suppliers/archive','SupplierController@archive')->name('suppliers.archive');
Route::resource('suppliers', 'SupplierController');


// Backup and restore
Route::get('backup', 'BackupController@index')->name('backup.index');
Route::get('backup/create', 'BackupController@create')->name('backup.create');
Route::get('backup/download/{file_name}', 'BackupController@download')->name('backup.download');
Route::get('backup/delete/{file_name}', 'BackupController@delete')->name('backup.delete');

resources/views/layouts/admin/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bwfurn</title>

    <!-- Bootstrap -->
    <link href="{{ asset('vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Font Awesome -->
    <link href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <!-- NProgress -->
    <link href="{{ asset('vendors/nprogress/nprogress.css') }}" rel="stylesheet" type="text/css">

    <link href="{{ asset('vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet" type="text/css">
    <!-- bootstrap-daterangepicker -->
    <link href="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('build/css/custom.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Datatables css -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css">


     <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        @include('layouts.admin.sidebar')

        <!-- top navigation -->
        @include('layouts.admin.header')
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
           @yield('content')
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        @include('layouts.admin.footer')
        <!-- /footer content -->
      </div>
    </div>
    <!-- Sweet Alert -->
    <script type="text/javascript" src="{{asset('js/sweeralert.js')}}"></script>
    <!-- jQuery -->
    <script type="text/javascript" src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script type="text/javascript" src="{{ asset('vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script type="text/javascript" src="{{ asset('vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script type="text/javascript" src="{{ asset('vendors/nprogress/nprogress.js') }}"></script>
    
    <!-- Custom Theme Scripts -->
    <script type="text/javascript" src="{{ asset('build/js/custom.min.js') }}"></script>

    <!-- Chart.js -->
    <script type="text/javascript" src="{{ asset('vendors/Chart.js/dist/Chart.min.js') }}"></script>
    <!-- jQuery Sparklines -->
    <script type="text/javascript" src="{{ asset('vendors/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
    <!-- morris.js -->
    <script type="text/javascript" src="{{ asset('vendors/raphael/raphael.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/morris.js/morris.min.js') }}"></script>
    <!-- gauge.js -->
    <script type="text/javascript" src="{{ asset('vendors/gauge.js/dist/gauge.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script type="text/javascript" src="{{ asset('vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- Skycons -->
    <script type="text/javascript" src="{{ asset('vendors/skycons/skycons.js') }}"></script>
    <!-- Flot -->
    <script type="text/javascript" src="{{ asset('vendors/Flot/jquery.flot.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/Flot/jquery.flot.pie.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/Flot/jquery.flot.time.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/Flot/jquery.flot.stack.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/Flot/jquery.flot.resize.js') }}"></script>
    <!-- Flot vendors -->
    <script type="text/javascript" src="{{ asset('vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/flot.curvedlines/curvedLines.js') }}"></script>
    <!-- DateJS -->
    <script type="text/javascript" src="{{ asset('vendors/DateJS/build/date.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script type="text/javascript" src="{{ asset('vendors/moment/min/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">$(document).ready(function(){
    $('#productsample').DataTable();
    $('#categorysample').DataTable();
    });
    // modal
    <!-- Dialog show event handler -->
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);
      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);

      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });

  <!-- Form confirm (yes/ok) handler, submits form -->
  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });
  
    </script>
    @yield('scripts')
  </body>
</html>

resources/views/layouts/admin/footer.blade.php
<footer class="footer_fixed">
  <div class="pull-right">

  </div>
  <div class="clearfix"></div>
</footer>

resources/views/layouts/admin/header.blade.php
<div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    @if (Auth::guest())
                    @else
                    <img src="{{asset('production/images/img.jpg') }}" alt="">
                    {{ Auth::user()->name }}
                    @endif
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li>
                      <a href="javascript:;">Help</a>
                    </li>
                    <li>
                    <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i>Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                  </li>
                  </ul>
                </li>

                
              </ul>
            </nav>
          </div>
        </div>

resources/views/layouts/admin/sidebar.blade.php
<div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{{url('/')}}" class="site_title"><i class="fa fa-paw"></i> <span>Bwfurn</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{ asset('production/images/img.jpg') }}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,
                @if (Auth::guest())
                @role('Admin') {{-- Laravel-permission blade helper --}}
                Admin
                @endrole</span>
                @else
                <h2>{{ Auth::user()->name }}</h2>
                @endif
              </div>
              <div class="clearfix"></div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="{{route('products.index')}}"><i class="fa fa-product-hunt"></i> Products</a></li>
                  <li><a href="{{route('categories.index')}}"><i class="fa fa-bars"></i> Categories</a></li>
                  <li><a href="{{route('suppliers.index')}}"><i class="fa fa-truck"></i> Suppliers</a>
                  </li>
                  <li><a href="{{route('inventory.list')}}"><i class="fa fa-list-alt"></i> Inventory</a>
                  </li>
                </ul>
              </div>
              <div class="menu_section">
                <h3>Others</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-archive"></i> Archive <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{route('products.archive')}}">Products</a></li>
                      <li><a href="{{route('categories.archive')}}">Categories</a></li>
                      <li><a href="{{route('suppliers.archive')}}">Suppliers</a></li>
                    </ul>
                  </li>
                  <li><a href="{{route('logs.index')}}"><i class="fa fa-history"></i> Logs</a>
                  </li>
                  <li><a><i class="fa fa-lock"></i> Administration Settings <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        
                        <li><a>Admin<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                            <li><a href="{{route('roles.index')}}">Roles</a>
                            </li>
                            <li><a href="{{route('permissions.index')}}">Permissions</a>
                            </li>
                          </ul>
                        </li>
                        <li><a href="{{route('users.index')}}">List of Admin</a>
                        </li>
                    </ul>
                    <li><a href="{{route('backup.index')}}"><i class="fa fa-edit"></i> Backup And Restore</a>
                  </li>                  
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>