routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'DashboardController@index')->name('home');
// Admin Security
Route::resource('logs', 'LogController');
Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');
// Product API
Route::put('product-restore/{id}','ProductController@rest')->name('products.restore');
Route::get('products/inventory','ProductController@listofinventory')->name('inventory.list');
Route::get('products/archive','ProductController@archive')->name('products.archive');
Route::get('products/create/raw','ProductController@createraw')->name('products.raw.create');
Route::resource('products', 'ProductController');
// Category API
Route::put('category-restore/{id}','CategoryController@rest')->name('categories.restore');
Route::get('categories/archive','CategoryController@archive')->name('categories.archive');
Route::resource('categories', 'CategoryController');
// Supplier API
Route::put('supplier-restore/{id}','SupplierController@rest')->name('suppliers.restore');
Route::get('suppliers/archive','SupplierController@archive')->name('suppliers.archive');
Route::resource('suppliers', 'SupplierController');


// Backup and restore
Route::get('backup', 'BackupController@index')->name('backup.index');
Route::get('backup/create', 'BackupController@create')->name('backup.create');
Route::get('backup/download/{file_name}', 'BackupController@download')->name('backup.download');
Route::get('backup/delete/{file_name}', 'BackupController@delete')->name('backup.delete');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Category;
use App\Supplier;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
	use SoftDeletes;

	protected $dates = ['deleted_at'];

	
    protected $fillable = [
        'code',
        'name', 
        'description', 
        'type',
        'category_id',
        'supplier_id', 
        'image',
        'quantity',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\Supplier;
use Session;
use App\Logs\Log;
use Carbon\Carbon;
use DB;
class ProductController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'clearance'])->except('index', 'show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index() 
    {
        $finished_products = Product::where('type','Featured Product')->orderby('id', 'desc')->get();
        $raw_products = Product::where('type','Raw Materials')->orderby('id', 'desc')->get();
        return view('products.index', compact('finished_products','raw_products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() 
    {   

        $categories = Category::all();
        $suppliers = Supplier::all();
        return view('products.create',[
            'categories'=> $categories,
            'suppliers'=> $suppliers
        ]);
    }

    public function createRaw()
    {
        $categories = Category::all();
        $suppliers = Supplier::all();
        return view('products.createraw',[
            'categories'=> $categories,
            'suppliers'=> $suppliers
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) 
    { 

    //Validating title and body field
        $this->validate($request, [
            'code'=>'required|unique:products|max:100',
            'name'=>'required|unique:products|max:100',
            'description' =>'required',
            'quantity' =>'required',
            'price' =>'required',
            'image' =>'image|mimes:jpeg,bmp,png|max:2000',
            ]);

        DB::table('logs')->insert([
            ['name' => 'Added '.$request->get('name').' in Products at '.\Carbon\Carbon::now()->format('M d, Y h:i a').'',
             'created_at' =>\Carbon\Carbon::now()->format('Y-m-d'), 
             'updated_at' =>\Carbon\Carbon::now()->format('Y-m-d')
         ]
        ]);

        $code = '';
        if ($request->type=="Finished Product"){
            $code = 'FP-0' .$request->id;
        }else{
            $code = 'RM-0' .$request->id;
        }
        $request->merge([
            'code' => $code
        ]);

        $product = Product::create($request->all());
    

    //Display a successful message upon save
        $request->session()->flash('message', $product->name. ' Created successful');
        return redirect()->back();


    }

    public function show($id) 
    {
        $product = Product::findOrFail($id); //Find product of id = $id

        return view ('products.show', compact('product'));
    }

    public function edit($id) 
    {
        $product = Product::with(['category'])->findOrfail($id);
        $categories = Category::all();

        return view('products.edit', compact('product','categories'));
    }

    public function update(Request $request, $id) 
    {
        $this->validate($request, [
            'code'=>'required|max:100',
            'name'=>'required|max:100',
            'description' =>'required',
            'quantity' =>'required',
            'price' =>'required',
            'image' =>'image|mimes:jpeg,bmp,png|max:2000',
            ]);

         DB::table('logs')->insert([
            ['name' => 'Updated '.$request->get('name').' in Products at '.\Carbon\Carbon::now()
            ->format('M d, Y h:i a').'',
             'created_at' =>\Carbon\Carbon::now()->format('Y-m-d'), 
             'updated_at' =>\Carbon\Carbon::now()->format('Y-m-d')
         ]
        ]);

       
        $product = Product::findOrFail($id)->update($request->all());


        $request->session()->flash('message','Updated successful');
        return redirect()->route('products.edit', $id);

    }

    public function destroy($id) {
        $product = Product::findOrFail($id);
        $product->delete();

        DB::table('logs')->insert([
            ['name' => 'Remove '.$product->name.' in Products at '.\Carbon\Carbon::now()->format('M d, Y h:i a').'',
             'created_at' =>\Carbon\Carbon::now()->format('Y-m-d'), 
             'updated_at' =>\Carbon\Carbon::now()->format('Y-m-d')
         ]
        ]);

        request()->session()->flash('message', 'Delete successful');
        return redirect()->route('products.index');

    }

    public function listofinventory()
    {
        $products = Product::with(['category','supplier'])->get();
        return view ('products.listofinventory',[
            'products' => $products
        ]);
    }

    public function archive()
    {
        $products = Product::onlyTrashed()
                    ->get();

        return view ('products.archive',[
            'products' => $products
        ]);
            
    }

    public function rest($id)
    {
        $product = Product::onlyTrashed()
                ->where('id', $id)
                ->restore();
        $product1 = Product::findOrfail($id);

        DB::table('logs')->insert([
        ['name' => 'Restore '.$product1->name.' in Products at '.\Carbon\Carbon::now()->format('M d, Y h:i a').'',
        'created_at' =>\Carbon\Carbon::now()->format('Y-m-d'), 
        'updated_at' =>\Carbon\Carbon::now()->format('Y-m-d')
        ]
        ]);

        request()->session()->flash('message', 'Restore successful');
        return redirect()->route('products.archive');
    }

}

resources/views/products/archive.blade.php
@extends('layouts.admin.app')
@section('content')
  @include('layouts.modal')
        <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Archive <small>List of Product Archive</small></h2>

                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="table-responsive">
                      @include('layouts.errors-and-messages')
                        <table class="table" id="productsample" >
                            <thead>
                                <th class="col-md-2">Code</th>
                                <th class="col-md-2">Name</th>
                                <th class="col-md-2">Description</th>
                                <th class="col-md-2">Quantity</th>
                                <th class="col-md-2">Price</th>
                                <th class="col-md-2">Action</th>
                            </thead>
                        <tbody>
                        @foreach ($products as $product)
                        <tr>
                            <td>{{ $product->code }}</td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->description }}</td>
                            <td>{{ $product->quantity }}</td>
                            <td>{{ $product->price }}</td>
                            <td>
                              <form action="{{ route('products.restore', $product->id) }}" method="POST" class="form-horizontal">

                              <input name="_method" type="hidden" value="PUT">
                              {{ csrf_field() }}

                              <div class="btn-group">
                                <button class="btn btn-success btn-sm edit" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Restore" data-message="Are you sure you want to restore ?"><i class="fa fa-check"></i>Restore</button>
                              </div>
                              </form>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                        </table>
                    </div>
                            
                        
                  </div>
                </div>
              </div>
@endsection

resources/views/products/create.blade.php
@extends('layouts.admin.app')

@section('content')
<section class="content">
        
    <div class="row">
        <div class="col-md-12">

                <div class="x_panel">
                  <div class="x_title">
                    <h2>Add Product <small>Products</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    @include('layouts.errors-and-messages')
                    <form action="{{ route('products.store') }}" method="post" class="form-horizontal form-label-left" enctype="multipart/form-data">
                      <div class="form-group">
                        {{ csrf_field() }}
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Code</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="code" placeholder="Product Code">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="name" placeholder="Product Name">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="description" placeholder="Description">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Quantity</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="quantity" placeholder="Product Quantity">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Price</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="price" placeholder="Product Price">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Type</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="type">
                            <option value="">Choose option</option>
                            <option value="Finished Product">Finished Product</option>
                            <option value="Raw Material">Raw Material</option>
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Category</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="category_id">
                            <option value="">Choose option</option>
                            @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Supplier</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="supplier_id">
                            <option value="">Choose option</option>
                            @foreach($suppliers as $supplier)
                            <option value="{{$supplier->id}}">{{$supplier->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Image</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="file" class="form-control" name="image">
                        </div>
                      </div>
                      

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                          <a href="{{route('products.index')}}" type="button" class="btn btn-primary">Cancel</a>
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
        </div>
</section>
@endsection

resources/views/products/createraw.blade.php
@extends('layouts.admin.app')

@section('content')
<section class="content">
        
    <div class="row">
        <div class="col-md-12">

                <div class="x_panel">
                  <div class="x_title">
                    <h2>Add Product <small>Products</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    @include('layouts.errors-and-messages')
                    <form action="{{ route('products.store') }}" method="post" class="form-horizontal form-label-left" enctype="multipart/form-data">
                      <div class="form-group">
                        {{ csrf_field() }}
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Code</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="code" placeholder="Product Code">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="name" placeholder="Product Name">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="description" placeholder="Description">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Quantity</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="quantity" placeholder="Product Quantity">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Price</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="price" placeholder="Product Price">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Type</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="type">
                            <option value="">Choose option</option>
                            <option value="Finished Product">Finished Product</option>
                            <option value="Raw Material">Raw Material</option>
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Category</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="category_id">
                            <option value="">Choose option</option>
                            @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Supplier</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="supplier_id">
                            <option value="">Choose option</option>
                            @foreach($suppliers as $supplier)
                            <option value="{{$supplier->id}}">{{$supplier->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Image</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="file" class="form-control" name="image">
                        </div>
                      </div>
                      

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                          <a href="{{route('products.index')}}" type="button" class="btn btn-primary">Cancel</a>
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
        </div>
</section>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<section class="content">
        
    <div class="row">
        <div class="col-md-12">

                <div class="x_panel">
                  <div class="x_title">
                    <h2>Edit Product <small>Products</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                      @include('layouts.errors-and-messages')
                    <form action="{{ route('products.update',$product->id) }}" method="post" class="form-horizontal form-label-left" enctype="multipart/form-data">
                      <div class="form-group">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="put">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Code</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="code" placeholder="Product Code" value="{!!$product->code ?: old('code')!!}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="name" placeholder="Product Name" value="{!!$product->name ?: old('name')!!}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="description" placeholder="Description" value="{!!$product->description ?: old('description')!!}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Quantity</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="quantity" placeholder="Product Quantity" value="{!!$product->quantity ?: old('quantity')!!}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Price</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="text" class="form-control" name="price" placeholder="Product Price" value="{!!$product->price ?: old('price')!!}">
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Category</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <select class="form-control" name="category_id">
                            <option value="{{$product->category->id}}">{{$product->category->name}}</option>
                            @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Image</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                          <input type="file" class="form-control" name="image">
                        </div>
                      </div>
                      

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                          <a href="{{route('products.index')}}" type="button" class="btn btn-primary">Cancel</a>
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>

                    </form>
                  </div>
                </div>
              </div>
        </div>
</section>
@endsection

resources/views/products/listofinventory.blade.php
@extends('layouts.admin.app')
@section('content')
  @include('layouts.modal')
        <div class="clearfix"></div>

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Inventory <small>List of Inventory</small></h2>

                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <th class="col-md-2">Code</th>
                                <th class="col-md-2">Name</th>
                                <th class="col-md-2">Category</th>
                                <th class="col-md-2">Supplier</th>
                                <th class="col-md-2">Description</th>
                                <th class="col-md-2">Quantity</th>
                                <th class="col-md-2">Price</th>
                            </thead>
                        <tbody>
                        @foreach ($products as $product)
                        <tr>
                            <td><a href="{{route('products.show',$product->id)}}">{{ $product->code }}</a></td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->category->name }}</td>
                            <td>{{ $product->supplier->name }}</td>
                            <td>{{ $product->description }}</td>
                            <td>{{ $product->quantity }}</td>
                            <td>{{ $product->price }}</td>
                            <td>                 
                        </tr>
                        @endforeach
                        </tbody>
                        </table>
                    </div>
                            
                        
                  </div>
                </div>
              </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.admin.app')

@section('title', '| View Product')

@section('content')

<div class="container">

    <h1>{{ $product->title }}</h1>
    <hr>
    <p class="lead">{{ $product->body }} </p>
    <hr>
    {!! Form::open(['method' => 'DELETE', 'route' => ['products.destroy', $product->id] ]) !!}
    <a href="{{ url()->previous() }}" class="btn btn-primary">Back</a>
    @can('Edit product')
    <a href="{{ route('products.index') }}" class="btn btn-info" role="button">Back</a>
    <a href="{{ route('products.edit', $product->id) }}" class="btn btn-info" role="button">Edit</a>
    @endcan
    @can('Delete Product')
    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
    @endcan
    {!! Form::close() !!}

</div>

@endsection